-- ========================================================
-- BANCO DE DADOS OFICIAL - FEDERAÇÃO PERNAMBUCANA FOOT TABLE
-- SUPABASE SQL SCHEMA COM POLÍTICAS RLS E SEED INICIAL
-- ========================================================

-- 1. TABELA DE ATLETAS FEDERADOS
CREATE TABLE IF NOT EXISTS public.atletas (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    codigo VARCHAR(6) UNIQUE NOT NULL,
    nome TEXT NOT NULL,
    cpf TEXT,
    nascimento TEXT,
    telefone TEXT,
    municipio TEXT,
    categoria TEXT DEFAULT 'AMADOR',
    modalidade TEXT DEFAULT 'SOLO (INDIVIDUAL)',
    status TEXT DEFAULT 'REGULAR',
    clube TEXT,
    federado TEXT,
    validade TEXT DEFAULT '12/2026',
    foto_url TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Suporte retroativo para bancos já criados
ALTER TABLE public.atletas 
ADD COLUMN IF NOT EXISTS categoria TEXT DEFAULT 'AMADOR',
ADD COLUMN IF NOT EXISTS telefone TEXT,
ADD COLUMN IF NOT EXISTS clube TEXT,
ADD COLUMN IF NOT EXISTS federado TEXT,
ADD COLUMN IF NOT EXISTS validade TEXT DEFAULT '12/2026';

-- Índices para busca ultra-rápida pelos 6 dígitos
CREATE INDEX IF NOT EXISTS idx_atletas_codigo ON public.atletas(codigo);

-- 2. TABELA DE NOTÍCIAS & TORNEIOS
CREATE TABLE IF NOT EXISTS public.noticias (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    titulo TEXT NOT NULL,
    categoria TEXT DEFAULT 'INFORMATIVO',
    conteudo TEXT NOT NULL,
    data_publicacao TEXT,
    imagem_url TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 3. TABELA DE KEEP-ALIVE (PING AUTOMÁTICO ANTI-PAUSA VERCEL)
-- Esta tabela recebe pings periódicos da Vercel para que o Supabase nunca entre em inatividade
CREATE TABLE IF NOT EXISTS public.keep_alive_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pinged_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    source TEXT DEFAULT 'vercel_cron',
    status TEXT DEFAULT 'active'
);

-- 4. TABELA DE GESTORES E E-MAILS INSTITUCIONAIS
CREATE TABLE IF NOT EXISTS public.admin_users (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    nome TEXT NOT NULL,
    cargo TEXT DEFAULT 'Diretoria',
    email TEXT UNIQUE NOT NULL,
    senha TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- ========================================================
-- POLÍTICAS DE SEGURANÇA (ROW LEVEL SECURITY - RLS)
-- ========================================================

ALTER TABLE public.atletas ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.noticias ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.keep_alive_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.admin_users ENABLE ROW LEVEL SECURITY;

-- Permite consulta pública aos dados de atletas (por código)
CREATE POLICY "Permitir leitura pública de atletas"
ON public.atletas FOR SELECT
TO anon, authenticated
USING (true);

-- Permite cadastro, edição e homologação de atletas pelo painel
CREATE POLICY "Permitir gerenciamento de atletas"
ON public.atletas FOR ALL
TO anon, authenticated
USING (true)
WITH CHECK (true);

-- Permite consulta pública às notícias
CREATE POLICY "Permitir leitura pública de notícias"
ON public.noticias FOR SELECT
TO anon, authenticated
USING (true);

-- Permite autenticação e criação de usuários institucionais
CREATE POLICY "Permitir acesso administradores"
ON public.admin_users FOR ALL
TO anon, authenticated
USING (true)
WITH CHECK (true);

-- Permite ping automático (INSERT e SELECT) no keep_alive_logs
CREATE POLICY "Permitir ping keep-alive"
ON public.keep_alive_logs FOR ALL
TO anon, authenticated
USING (true)
WITH CHECK (true);

-- ========================================================
-- DADOS INICIAIS (SEED)
-- ========================================================

-- Inserir Atletas Padrão
INSERT INTO public.atletas (codigo, nome, cpf, nascimento, municipio, modalidade, status, foto_url)
VALUES 
    ('742918', 'Matheus Vinicius Ferraz', '123.456.789-00', '14/05/1998', 'Recife - PE', 'SOLO (INDIVIDUAL)', 'REGULAR', 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=300&q=80'),
    ('581902', 'Camila Duarte Silveira', '987.654.321-11', '22/11/2001', 'Olinda - PE', 'DUPLA (EQUIPE)', 'REGULAR', 'https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=300&q=80')
ON CONFLICT (codigo) DO NOTHING;

-- Inserir Notícias Padrão
INSERT INTO public.noticias (titulo, categoria, conteudo, data_publicacao)
VALUES 
    ('II Campeonato Mundial de Futebol de Mesa — Roma aguarda seus novos campeões', 'MUNDIAL ROMA', 'O Campeonato Mundial começa de 1 a 4 de outubro em Roma, Itália, com mais de 50 países competindo em todas as categorias de Foot Table.', '28/09/2026'),
    ('Vitória Fernandes chega a Roma como a mulher a ser batida no circuito mundial', 'CAMPEONATO', 'A estrela brasileira lidera os rankings mundiais de simples e duplas femininas com 2.000 pontos acumulados na temporada.', '25/09/2026'),
    ('Homologado o regulamento oficial de quadras e mesas curvas para a temporada pernambucana', 'REGULAMENTO', 'A Federação Pernambucana publicou as diretrizes técnicas atualizadas de saque e altura das redes centrais para torneios oficiais.', '20/09/2026')
ON CONFLICT DO NOTHING;

-- Registro de ativação inicial do Keep Alive
INSERT INTO public.keep_alive_logs (source, status)
VALUES ('initial_setup', 'active');
